export const RETRIEVE_DOCUMENT_LIST = "RETRIEVE_DOCUMENT_LIST";

// CRUD Document
export const CREATE_DOCUMENT = "CREATE_DOCUMENT";
export const RETRIEVE_DOCUMENT = "RETRIEVE_DOCUMENT";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

// CRUD ERROR
export const CRUD_DOC_ERROR = "CRUD_DOC_ERROR";
