export const CRUD_DOC_ERROR = "CRUD_DOC_ERROR";
export const CRUD_DOC_COMPLAINT_ERROR = "CRUD_DOC_COMPLAINT_ERROR";
export const CRUD_USER_COMPLAINT_ERROR = "CRUD_USER_COMPLAINT_ERROR";
export const TABOO_ERROR = "TABOO_ERROR";
