export const CREATE_PROMOTION = "CREATE_PROMOTION";
export const RETRIEVE_ALL_PROMOTION = "RETRIEVE_ALL_PROMOTION";
export const APPROVE_USER_PROMOTION = "APPROVE_USER_PROMOTION";
export const DENY_USER_PROMOTION = "DENY_USER_PROMOTION";
export const PROMOTE_USER = "PROMOTE_USER";
export const DEMOTE_USER = "DEMOTE_USER";
