export const CREATE_TABOO_WORD = "CREATE_TABOO_WORD";
export const RETRIEVE_APPROVED_TABOO_WORDS = "RETRIEVE_APPROVED_TABOO_WORDS";
export const RETRIEVE_UNAPPROVED_TABOO_WORDS = "RETRIEVE_UNAPPROVED_TABOO_WORDS";
export const APPROVE_TABOO_WORD = "APPROVE_TABOO_WORD";
export const DELETE_TABOO_WORD = "DELETE_TABOO_WORD";
