export const RETRIEVE_DOC_COMPLAINT_LIST = "RETRIEVE_DOC_COMPLAINT_LIST";
export const PROCESS_DOC_COMPLAINT = "PROCESS_DOC_COMPLAINT";
export const RETRIEVE_DOC_COMPLAINT = "RETRIEVE_DOC_COMPLAINT";
export const RESET_DOC_COMPLAINT = "RESET_DOC_COMPLAINT";
