export const RETRIEVE_USER_COMPLAINT_LIST = "RETRIEVE_USER_COMPLAINT_LIST";
export const PROCESS_USER_COMPLAINT = "PROCESS_USER_COMPLAINT";
export const RETRIEVE_USER_COMPLAINT = "RETRIEVE_USER_COMPLAINT";
export const RESET_USER_COMPLAINT = "RESET_USER_COMPLAINT";
