export const RETRIEVE_DOCUMENT_LIST = "RETRIEVE_DOCUMENT_LIST";

// CRUD Document
export const CREATE_DOCUMENT = "CREATE_DOCUMENT";
export const RETRIEVE_DOCUMENT = "RETRIEVE_DOCUMENT";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

// CRUD ERROR
export const CRUD_DOC_ERROR = "CRUD_DOC_ERROR";

// Lock-Unlock Document
export const LOCK_DOCUMENT = "LOCK_DOCUMENT";
export const UNLOCK_DOCUMENT = "UNLOCK_DOCUMENT";

// Lock-Unlock Error
export const LOCK_ERROR = "LOCK_ERROR";
export const UNLOCK_ERROR = "UNLOCK_ERROR";

// Invitation
export const INVITATION_SUCCESSFUL = "INVITATION_SUCCESSFUL";
export const INVITATION_UNSUCCESSFUL = "INVITATION_UNSUCCESSFUL";

// Remove User From Document
export const REMOVE_USER_FROM_DOC_SUCCESSFUL = "REMOVE_USER_FROM_DOC_SUCCESSFUL";
export const REMOVE_USER_FROM_DOC_UNSUCCESSFUL = "REMOVE_USER_FROM_DOC_UNSUCCESSFUL";

// Set Privacy Settings on Document
export const SET_PRIVACY_SUCCESSFUL = "SET_PRIVACY_SUCCESSFUL";
export const SET_PRIVACY_UNSUCCESSFUL = "SET_PRIVACY_UNSUCCESSFUL";
