// CRUD Profiles
export const CREATE_PROFILE = "CREATE_PROFILE";
export const RETRIEVE_PROFILE = "RETRIEVE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";

// Profile List
export const RETRIEVE_PROFILE_LIST = "RETRIEVE_PROFILE_LIST";
