// CRUD User Complaints
export const CREATE_USER_COMPLAINT = "CREATE_USER_COMPLAINT";
export const PROCESS_USER_COMPLAINT = "PROCESS_USER_COMPLAINT";
export const RETRIEVE_USER_COMPLAINT = "RETRIEVE_USER_COMPLAINT";
export const DELETE_USER_COMPLAINT = "DELETE_USER_COMPLAINT";

// Options
export const RESET_USER_COMPLAINT = "RESET_USER_COMPLAINT";

// User Complaint List
export const RETRIEVE_USER_COMPLAINT_LIST = "RETRIEVE_USER_COMPLAINT_LIST";
