
export const COMPLAINT_MANAGER_CONTAINER = "COMPLAINT_MANAGER_CONTAINER";
export const DOCUMENT_CONTAINER = "DOCUMENT_CONTAINER";
export const DOCUMENT_MANAGER_CONTAINER = "DOCUMENT_MANAGER_CONTAINER";
export const HOME_CONTAINER = "HOME_CONTAINER";
export const LOGIN_CONTAINER = "LOGIN_CONTAINER";
export const PROFILE_MANAGER_CONTAINER = "PROFILE_MANAGER_CONTAINER";
export const SIGNUP_CONTAINER = "SIGNUP_CONTAINER";
export const TABOO_WORD_MANAGER_CONTAINER = "TABOO_WORD_MANAGER_CONTAINER";
